services:
  rust-api-template:
    image: neko7nik/rust-api-template:latest
    container_name: rust-api-template

    environment:
      - TZ=Asia/Kolkata

      # Logging and Runtime
      - RUST_LOG=rust_api=TRACE
      - API_WORKERS_COUNT=4

      # PostgreSQL Database
      - POSTGRES_DB_URL=postgres://user:password@db.nekonik.com:5432/nekonik
      - POSTGRES_DB_MAX_POOL_SIZE=100

      # In-Memory Cache
      - CACHE_MAX_CAPACITY=1000
      - CACHE_TIME_TO_LIVE=300

    ports:
      - "127.0.0.1:8686:8686"

    restart: always
