services:
  rust-api-template:
    image: neko7nik/rust-api-template:latest
    container_name: rust-api-template

    environment:
      - TZ=Asia/Kolkata
      - RUST_LOG=rust_api=TRACE
      - SERVER_WORKERS_COUNT=2
      - POSTGRES_DB_URL=postgres://user:password@db.nekonik.com:5432/neko
      - POSTGRES_DB_MAX_POOL_SIZE=10

    ports:
      - "127.0.0.1:8686:8686"

    restart: always
